#!/bin/sh

tmux new-session -d -n 'python-dev'
tmux split-window -v -p 30
tmux new-window -n 'git'
tmux select-window -t 1
tmux select-pane -t 1
tmux send-keys -t 1 'vim -c Exp' Enter
tmux -2 attach-session -d
